apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
  namespace: argocd
spec:
  destination:
    namespace: bgd
    server: https://kubernetes.default.svc
    project: default
    server:
      repoURL: https://github.com/byj1009/gitops-cookbook-sc.git
      path: ch07/bgd
      targetRevision: main